vscode:
  extensions:
    - webfreak.code-d
    - grammarcraft.epsilon-eag-extension-pack@2.2.0
    - grammarcraft.epsilon-eag@2.2.0
    - grammarcraft.epsilon-eag-dark-theme@2.2.0
    - grammarcraft.epsilon-eag-light-theme@2.2.0

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run tests
    init: dub test
  - name: Compile gamma
    init: dub build
